consul:
  image: progrium/consul:latest
  command: -server -bootstrap -ui-dir /ui
  mem_limit: 256m
  ports:
  - 53
  - 8300
  - 8301
  - 8302
  - 8400
  - 8500
  dns:
    - 127.0.0.1
  restart: always

helloworld:
  build: ./helloworld
  ports:
    - "3000"
  links:
    - consul
  environment:
    SERVICE_NAME: helloworld
    SERVICE_TAGS: production

lb:
  build: ./lb
  links:
    - consul
  ports:
    - "80:80"
  volumes:
    - ./lb/templates:/etc/consul-templates